#!/bin/bash

# See if networkmanager has a connection
# Returns 0 if connected, 1 if not connected
# --timeout en segundos, da tiempo a la auto conexión
nm-online --timeout 10

not_connected=$?

if [ $not_connected -eq 1 ]; then
  echo Not connected
  wifi-connect -a 60
else
  echo Connected
fi
